# Устранение ошибок с HTTP 499 при работе облачной функции или контейнера {{ serverless-containers-name }}


## Описание проблемы {#issue-description}

В журнале работы облачной функции или контейнера {{ serverless-containers-name }} отображаются сообщения вида `Error: Code 499 Message: request cancelled`.

## Решение {#issue-resolution}

Такое поведение происходит, когда функция разрывает соединение до того, как ей был отправлен ответ со стороны сервера. Такое может происходить, если по истечении таймаута на один запрос в функции запрос отменяется, поэтому в логах отображается строка `Request cancelled`.

Выполните следующие действия для решения проблемы:

1. Добавьте логирование в код функции. Мы подготовиили пример настройки логирования работы облачных функций на Python [в документации](../../../functions/lang/python/logging.md).
1. Переработайте логику работы функции. Хорошей практикой является использовать разные методы API разными сервисными аккаунтами. Если по каким-то причинам — система безопасности, устаревание токена и так далее — у аккаунта, от чьего имени происходит обращение к API, пропадет доступ, то проблемы возникнут лишь с одним или несколькими методами функции, а не со всей функцией сразу. Кроме того, такой подход поможет упростить диагностику функции, если с ней возникнут другие проблемы в будущем.

## Если проблема осталась {#if-issue-still-persists}

Если вышеописанные действия не помогли решить проблему, [создайте запрос в техническую поддержку]({{ link-console-support }}). При создании запроса укажите следующую информацию:

1. Идентификатор облачной функции или контейнера {{ serverless-containers-name }}.
1. Содержимое журнала работы облачной функции или контейнера. Журналы работы функции доступны в разделе **{{ ui-key.yacloud.serverless-functions.item.switch_logs }}** на странице функции в [Консоли управления]({{ link-console-main }}).
